# ──────────────────────────────────────────
# Orders table
#
# Schema:
#   PK  order_id (String) — partition key, UUID generated by create-order Lambda
#
# GSI: status-created_at-index:
#   PK  status      (String) — query all orders by status (PENDING/PROCESSING/COMPLETED/FAILED)
#   SK  created_at  (String) — sort within a status by ISO-8601 timestamp
#
# GSI: customer_id-created_at-index:
#   PK  customer_id     (String) — query all orders for a given customer
#   SK  created_at  (String) — sort within a customer by ISO-8601 timestamp
#
# All other attributes (customer_id, items, total, etc.) are schemaless —
# ──────────────────────────────────────────

resource "aws_dynamodb_table" "orders" {
  name         = "${var.prefix}-orders"
  billing_mode = var.billing_mode
  hash_key     = "order_id"

  # Only set capacity when billing mode is PROVISIONED
  read_capacity  = var.billing_mode == "PROVISIONED" ? var.read_capacity : null
  write_capacity = var.billing_mode == "PROVISIONED" ? var.write_capacity : null

  # Primary key
  attribute {
    name = "order_id"
    type = "S"
  }

  # GSI attributes — must be declared even though they are not the table PK
  attribute {
  name = "customer_id"
  type = "S"
  }

  attribute {
    name = "status"
    type = "S"
  }

  attribute {
    name = "created_at"
    type = "S"
  }

  # GSI — query orders by status, sorted by creation time
  # e.g. "give me all FAILED orders, newest first"
  global_secondary_index {
    name            = "status-created_at-index"
    hash_key        = "status"
    range_key       = "created_at"
    projection_type = "ALL"

    # Only needed for PROVISIONED billing
    read_capacity  = var.billing_mode == "PROVISIONED" ? var.read_capacity : null
    write_capacity = var.billing_mode == "PROVISIONED" ? var.write_capacity : null
  }

  # GSI — query orders by customer, sorted by creation time
  # e.g. "give me all orders for customer X, newest first"
  global_secondary_index {
    name            = "customer_id-created_at-index"
    hash_key        = "customer_id"
    range_key       = "created_at"
    projection_type = "ALL"

    read_capacity  = var.billing_mode == "PROVISIONED" ? var.read_capacity : null
    write_capacity = var.billing_mode == "PROVISIONED" ? var.write_capacity : null
  }

  # TTL — when enabled, DynamoDB automatically deletes items
  # whose `expires_at` epoch timestamp is in the past
  ttl {
    enabled        = var.ttl_enabled
    attribute_name = var.ttl_attribute
  }

  # Point-in-time recovery — enables restore to any second
  # within the last 35 days. Always on in prod, off in dev to save cost.
  point_in_time_recovery {
    enabled = var.point_in_time_recovery
  }

  # Encrypt table at rest using AWS-managed key
  server_side_encryption {
    enabled = true
  }
}

# ──────────────────────────────────────────
# CloudWatch alarms
# ──────────────────────────────────────────

# Alert when DynamoDB returns system errors (5xx)
# These indicate AWS-side issues, not application bugs
resource "aws_cloudwatch_metric_alarm" "system_errors" {
  alarm_name          = "${var.prefix}-dynamodb-system-errors"
  alarm_description   = "DynamoDB is returning system errors on the orders table"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 1
  metric_name         = "SystemErrors"
  namespace           = "AWS/DynamoDB"
  period              = 60
  statistic           = "Sum"
  threshold           = 0
  treat_missing_data  = "notBreaching"

  dimensions = {
    TableName = aws_dynamodb_table.orders.name
  }
}

# Alert on throttling — means traffic is exceeding capacity
# Only relevant when billing_mode = PROVISIONED, but harmless on PAY_PER_REQUEST
resource "aws_cloudwatch_metric_alarm" "throttled_requests" {
  alarm_name          = "${var.prefix}-dynamodb-throttling"
  alarm_description   = "DynamoDB requests are being throttled on the orders table"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 2
  metric_name         = "ThrottledRequests"
  namespace           = "AWS/DynamoDB"
  period              = 60
  statistic           = "Sum"
  threshold           = 0
  treat_missing_data  = "notBreaching"

  dimensions = {
    TableName = aws_dynamodb_table.orders.name
  }
}
